In [1]:
import numpy as np

In [2]:
# Problems (Soal) X -> x1,x2,x3, Y -> the results
Xaxis = [
    [
      [6,2,3],
      [5,8,2],
      [4,3,9]
    ],
    [
      [1,1,1,1],
      [2,2,2,2],
      [3,3,3,3],
      [4,4,4,4]
    ]
]

Yaxis = [
    [
      31,
      38,
      31
    ],
    [
      5,
      5,
      5,
      5
    ]
]

In [18]:
def checkDom(A):
    
    A = np.array(A)
    diag = np.diag(abs(A))

    non_diag = np.sum(abs(A), axis = 1)
    non_diag -= diag

    if np.all(diag > non_diag):
        return True
    else:
        return False

In [10]:
def gauss_seidel(A,B,epsilon = 0.0001, max_iteration = 20):
    
    A = np.array(A)
    B = np.array(B)

    result = np.zeros(A.shape[0])
    diag = np.diag(A)
    A = -A
    np.fill_diagonal(A,0)

    for i in range(max_iteration):
        result_new = np.array(result)
        for j, row in enumerate(A):
            result_new[j] = (B[j] + np.dot(row,result_new))/diag[j]
        result_new = np.array(result_new)
        dist = np.sqrt(np.dot(result_new-result,result_new-result))
        print(f"Iteration {i+1}: {result_new}")
        if dist < epsilon:
            print("")
            print(f"Solution: {result_new}")
            return True
        else:
            result = result_new
    return False

In [19]:
for i, (x,y) in enumerate(zip(Xaxis,Yaxis)):
    print(f"Problem {i+1}")
    print(f"X-Axis: {x}")
    print(f"Y-Axis: {y}")
    if checkDom(x):
        print("Dominant")
        if gauss_seidel(x,y):
            print("Convergent")
        else:
            print("Not convergent")
    else:
        print("Not Dominant")
        

Problem 1
X-Axis: [[6, 2, 3], [5, 8, 2], [4, 3, 9]]
Y-Axis: [31, 38, 31]
[[6 2 3]
 [5 8 2]
 [4 3 9]]
Dominant
Iteration 1: [5.16666667 1.52083333 0.6412037 ]
Iteration 2: [4.33912037 1.87774884 0.89003022]
Iteration 3: [4.09573528 1.9676579  0.96823169]
Iteration 4: [4.02666486 1.99127654 0.99105677]
Iteration 5: [4.00737943 1.99762366 0.99751236]
Iteration 6: [4.00203593 1.99934945 0.99931199]
Iteration 7: [4.00056085 1.99982147 0.99981024]
Iteration 8: [4.00015439 1.99995095 0.99994773]
Iteration 9: [4.00004248 1.99998651 0.99998561]
Iteration 10: [4.00001169 1.99999629 0.99999604]

Solution: [4.00001169 1.99999629 0.99999604]
Convergent
Problem 2
X-Axis: [[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]]
Y-Axis: [5, 5, 5, 5]
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
Not Dominant
