In [2]:
print("""\
@@@@@@@@@@@@@@@@@%#*******++*+++++++++*****####%@@@@@@@@@@@@@@@@@@@@@@%%%%#+=-----------------:-::::
@@@@@@@@@@@@@@@@@@@@@@%###*****###********###%%%%@@@@@@@%%%%%@@%%%%%%%%%#=---------=----------::::::
@@@@@@@@@@@@@@@@@@@@@@@@@@@%*##%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%#+=--------======-------:::::::
%%%%%%%@@@@@@@@@@@@@@@@@@@@%#%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#+=---------=======-----::::::::::
%%%%%%%%@@@@@@@@@@@@@@@@@@@%%%##%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#+--------==========-----:::::::::::
%%%%%%%%%@@@@@@@%%%%%%%%@%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%*-:------===========---::::::::::::::
%%%%%%%%@@@@@%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%=-:.:-----==========---:::::::::::::::
%%%%%@@@@@@%%%######%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%#+-::..::----========---::::::::::::::::
%%%%%%%%%%%###########%%%%%%%%%%#%%%%%%%%%%%%%%##**+++++***###%%@@@@*::-----====--:-:-::::::::::::::
**#####***#############%%%%%%%%%#*++==-=+*#%@@@@@@@@@@@@@@@@@@@@@@@@@@@*::----=---::-:::::::::::::::
*****#*******###########%%%%%%%%##++%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#-:---::---:::::::::::::::
*****##******###########%%%%%%%%#####=-%@@@@@@@@@@@%+--===+*#%%@@@@@@@@@@@@@@%-::---::::::::::::::::
***#####*****############%%%%%%%#*+====-:-*@@@@@%+#@@@@@@@@@@@@@%##*++#@@@@@@@@@%+::::::::::::::::::
****####*******##########%%%%#*=======---===:#@-%@@@@@@@@@@@@@@@@@@@@@@@%==#@@@@@@@@=:::::::::::::::
*****#####*****############*==-======---=+++*=*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#+*@@@@@@%+::::::::::::
*****#####******#########+-=========--=++++*-%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*#@@@@@@@@@+:::::::::
**#**#####**##########*=--========-:-=+++**=@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*#@@@@@@@@@@@*::::::
***#**#########*#####*---========-:-==++**+*%%####%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*%@@@@@@@@%%#*+::::
***##*########***###*---=======-:-==+++****=-+++**##*+=++%@@@@@@@@@@@@@@@@@@@@@@@%-.=:::::::::::::::
***##*#########*###*-:--======:-==++++**++++*++++*###****#*-=%@@@@@@@@@@@@@@@@@@@@=-:*=:---:::::::::
***##**##########*+::--====+=:.:-========**=::-+****##############**###**+++*+*@@@+---:-+:----::::::
***##############+:::-====++-:-::--====+++::=*#*=+*###########**###%######%%%%%%==*-=--=+:----------
*########%%%####=:::--==++++:-=----===++-:-+*+====####**#*##%#%***##%%#++*##%%%%%%%*--+=------------
##%%%%###%%%%%#=::::--=+++++:=+====--==:::------=+*##*****%@@@#*++*##%%#*==++*%%%%**%==++====-------
#%%%%%#%%##%#*=:::::-==+++++:+++=====-:.::-::.::::-=+**####%%#+==+**##%%##+==+*##+%@*============---
%%%%%%%%##*==-::-----=+++**+-+++++=++:.::-:........:-=========--==++***###*++==-%@@:*+==-===========
%%%%%%%*+=---:::::--==++***+-=+=+++*-..::-::::..:.::-=+=---::::::--=++++*#**+=+@%%+#*===----========
%%@@#+=-----:---:--:-=++**+==--++**+:.:::::-:-:--:===**++=:::::::--===++*#++-#@*-++##+==-------=====
%#+=-------::-------:=+***+==-:=+++-.::::::-=---=+-::---==+--::::--==+++***=#@#:.-+**====---------==
=-------:::.-------=-=+*##+++=-=++=:.:::::-===-:::::::-++===++-:::====+++*-#@@:.=:=#+==--=----------
---:::::::.:--==--==:=+**#+++==+++=:.::---::::::.....:-+=-=-=*+=+====+++*++-==--===*==-=------------
::::::::::::-======-:=+*#*+++++++==:::::--=:::::::...:.::::::-==+*+======+=======++*=---------------
::::::..:::-=======-:=+**#++++++++=:.::::::--::---=::::::::::::--==+++====+====-=++++---------------
::.:::--::-====+==+=:=+**#*+++++++=-::.:::::::---=--:------==-----===++-----====+++*+-----------====
:::::::::-===++===+=-=+****+++++++==-::::::::::-------=---=+=--==-====++=++===++=*#*=----------=====
........-==++======+-=+*++=++++=++===-:::::::::::----====+++=+=++=====++=+*==++++++=-------:-----===
.......:=++++=====++-+**++==++++++====-:::::::::::----=+=+======+===++========+++=------------------
......:-=+++====++======*======++======--:::::::::-:---=-======-============+**#+=-----:----=-------
.::...-=++++=======++==+*=-===++=+=======--:-:-:::::::::-----========--=-==++*-:-=---------==-------
.....:-=+++======+****+*+=====++++===========-:---:--:-:--:----======-==-==++:..:-====----======----
....:-==++====+**#****#*=======+==+=++====-==-=------------------=-=---=-==+=:..::=+=============---
:::.:-======+*###****##++=--=+=+++=+=++===========---=-===-----------=====+*=-:::::+**+=============
-:...-=+=+**#####***##*++====-===++=+=++============--======-============+++====---=+++++++++=======
....:=++*#############**+++==+=====++++=+=====-==-==-========+===========--======---=====++**+++++++
...:=+******##########**+++++++++=+==+++======-=----=======-===========---===+++==-:-=======*##****+
.:-+******++#%#########***+++++++*++++=+++=====--=---======---==-====+---=====+++============+*%%%%%
-+********#############*****++*+*++*++=+=+======-----=-----===========--======+++++============+#%%%
+***+###%%%##########********++*++++++++======-=-=-=-=--=--==========-====+=+++++++++============*#%
=**=-**################*****+++++++++++++======-====-=-=--=-====++===-===+++++++++**+=============+#
===:=#####*#####%######****++++++++++++++++=+===+======-========++++=-====++++++++***+=======++=====
+=++*###**###%%%%%%%%###*****+++++++++++==+=-====+============++++*+--=====+++++++***+====-==+++====
=*+*#%%****##%%%%%%%%%%##****+++++=+=+==+====--=-=---=======++*****=---=====++++++****+===-====++===
++#%@%*+***#%%%%@@@@@%%%##*******+++++======-=--===========++**####:----====++++++*****+=======+++==
#%@@@*++**##%%%@@@@@@%%%#####*****++++++=+============+++++*****##+:----====+++++++****++=======++++
%@@@%+++*##%%%@@@@@@%%%#######****+*++++++=========++++++++***####-------====+++++++****+=======++++
%%@@*+**##%%@@@@@@%%%%%#####*********++++=+========++++*++****##%#-------====++++++++***++=======+++
#%%%++*##%%@@@@@@@%%%%%###******++++++++++=++====++++++*****###%%*=-------===+++++++++***++=======++
##%*+*#%%%@@@@@@@%%%%%%###********+*++++++++++++++++++*****###%%%*==----=====++++++++++***+=======++
###+*#%%%@@@@@@@%%%%%#%###**********++++++++++++++++*******#####%*===---====++++++++++*****+========
      """)

@@@@@@@@@@@@@@@@@%#*******++*+++++++++*****####%@@@@@@@@@@@@@@@@@@@@@@%%%%#+=-----------------:-::::
@@@@@@@@@@@@@@@@@@@@@@%###*****###********###%%%%@@@@@@@%%%%%@@%%%%%%%%%#=---------=----------::::::
@@@@@@@@@@@@@@@@@@@@@@@@@@@%*##%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%#+=--------======-------:::::::
%%%%%%%@@@@@@@@@@@@@@@@@@@@%#%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#+=---------=======-----::::::::::
%%%%%%%%@@@@@@@@@@@@@@@@@@@%%%##%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#+--------==========-----:::::::::::
%%%%%%%%%@@@@@@@%%%%%%%%@%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%*-:------===========---::::::::::::::
%%%%%%%%@@@@@%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%=-:.:-----==========---:::::::::::::::
%%%%%@@@@@@%%%######%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%#+-::..::----========---::::::::::::::::
%%%%%%%%%%%###########%%%%%%%%%%#%%%%%%%%%%%%%%##**+++++***###%%@@@@*::-----====--:-:-::::::::::::::
**#####***#############%%%%%%%%%#*++==-=+*#%@@@@@@@@@@@@@@@@@@@@@@@@@@@*::----=---::-::::::

In [3]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

print(np.ndim(arr))

[[1 2 3 4]
 [5 6 7 8]]
2


In [4]:
arrZero = np.zeros([3,3],dtype=int)
print(arrZero)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
arrOnes = np.ones([3,3],dtype=int)
print(arrOnes)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
arrEmpty = np.empty([2,2], dtype=int)
print(arrEmpty)

[[-1196819603   401891464]
 [ -748502516   976264250]]


In [7]:
import cv2

In [10]:
# imread -> read image and store it in a variable
# imshow -> show the image in a window
# imwrite -> save an image in a given directory
image_path = "OtterGraduate.png"
image = cv2.imread(image_path)

#grayscale
gray_image = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

cv2.imshow('Hehe Sleepy Gray', gray_image)

cv2.imshow('Hehe Sleepy', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
output_path = './processed_image.png'
cv2.imwrite(output_path, gray_image)

True